### ISSUE TITLE
⚙️ Phase 4: Linux Context Menu Implementation

### ISSUE THREAD

**Issue by bekaIva** [bekaIva/instant_ai_translator#5]
# Phase 4: Linux Context Menu Implementation

## 🎯 Objective
Implement the actual system-wide context menu integration for Linux desktop environments, based on research findings from Phase 2.

### 1. Native System Integration Module
- [ ] **Create Native Library**
  - Develop C/C++ or Rust library for system hooks
  - FFI (Foreign Function Interface) bindings for Flutter
  - Cross-compilation for different architectures

### 2. Text Selection Monitoring
- [ ] **Primary Selection Capture (X11)**
  ```c
  // Monitor X11 primary selection changes
  void monitor_selection_changes() {
    // XSelectInput with SelectionNotify events
    // Capture selected text automatically
  }
  ```
- [ ] **Accessibility API Integration**
  - AT-SPI text selection monitoring
  - Real-time text capture from focused applications
  - Support for both X11 and Wayland

### 3. Context Menu Injection
- [ ] **GTK-based Applications**
  - GTK menu extension mechanism
  - Runtime menu modification
  - Custom menu items with callbacks
- [ ] **Qt-based Applications**
  - Qt plugin system integration
  - QMenu modification hooks
  - Cross-application compatibility
- [ ] **Universal Fallback**
  - Global hotkey activation (Ctrl+Alt+T)
  - Floating context menu overlay
  - Position-aware menu placement

### 4. Inter-Process Communication
- [ ] **D-Bus Service Implementation**
  ```xml
  <!-- D-Bus interface definition -->
  <interface name="com.instantai.Translator">
    <method name="ProcessText">
      <arg direction="in" type="s" name="text"/>
      <arg direction="in" type="s" name="operation"/>
      <arg direction="out" type="s" name="result"/>
    </method>
  </interface>
  ```
- [ ] **Message Protocol Design**
  - Text processing requests
  - Operation type specification
  - Result delivery and error handling

### 5. Text Replacement Engine
- [ ] **Clipboard-based Replacement**
  - Store original clipboard content
  - Replace with processed text
  - Restore original clipboard
- [ ] **Direct Application Injection**
  - Send key events to simulate paste
  - Handle different paste mechanisms
  - Undo/redo support where possible

### 1. Native System Hook Library (`libinstant_translator.so`)
```c
// Core functions to be implemented
typedef struct {
    char* text;
    int x, y;           // Selection coordinates
    char* app_name;     // Source application
} SelectionData;

// Function exports for Flutter FFI
extern "C" {
    int init_system_hooks();
    void cleanup_system_hooks();
    int register_context_menu(const char* menu_items[]);
    SelectionData* get_current_selection();
    int replace_selection(const char* new_text);
}
```

### 2. Flutter FFI Bindings
```dart
// lib/native/system_integration.dart
import 'dart:ffi';

class SystemIntegration {
  static final DynamicLibrary _lib = DynamicLibrary.open('libinstant_translator.so');
  
  static final _initHooks = _lib.lookupFunction<Int32 Function(), int Function()>('init_system_hooks');
  static final _registerMenu = _lib.lookupFunction<Int32 Function(Pointer<Pointer<Utf8>>), int Function(Pointer<Pointer<Utf8>>)>('register_context_menu');
  
  static bool initializeSystemHooks() {
    return _initHooks() == 0;
  }
  
  static bool registerContextMenu(List<String> menuItems) {
    // Implementation for menu registration
  }
}
```

### 3. Context Menu Configuration
- [ ] **Menu Item Management**
  - Dynamic menu item creation
  - User-customizable menu options
  - Icon and accelerator key support
- [ ] **Operation Mapping**
  - Menu item to processing function mapping
  - Custom operation definitions
  - Per-application menu customization

#### GNOME/GTK Support
- [ ] **GTK Extension Module**
  - GMenu integration
  - GNOME Shell extension compatibility
  - Wayland support via GDK

#### KDE/Qt Support
- [ ] **Qt Plugin Implementation**
  - KDE Plasma integration
  - QML-based menu extensions
  - KRunner integration for fallback

#### Universal X11 Support
- [ ] **Xlib-based Implementation**
  - Window manager agnostic
  - Basic X11 selection monitoring
  - Minimal dependencies

### 1. Application Compatibility Testing
- [ ] **Text Editors**
  - VS Code, Atom, Sublime Text
  - Vim/Neovim, Emacs
  - gedit, Kate, nano
- [ ] **Office Applications**
  - LibreOffice Writer, Calc
  - Google Docs (browser)
  - Markdown editors
- [ ] **Communication Apps**
  - Slack, Discord, Telegram
  - Email clients (Thunderbird, Evolution)
  - Chat applications

### 2. Desktop Environment Testing
- [ ] **GNOME** (Ubuntu, Fedora)
- [ ] **KDE Plasma** (openSUSE, Kubuntu)
- [ ] **XFCE** (Xubuntu)
- [ ] **i3/Sway** (tiling window managers)

### 3. Performance Testing
- [ ] **Response Time Measurements**
  - Menu injection latency
  - Text processing speed
  - Memory usage monitoring
- [ ] **Stability Testing**
  - Long-running system integration
  - Memory leak detection
  - Error recovery testing

### 1. Permission Management
- [ ] **Minimal Privilege Principle**
  - Request only necessary permissions
  - Runtime permission requests
  - User consent for system integration

### 2. Data Privacy
- [ ] **Local Processing Priority**
  - Process sensitive text locally when possible
  - Clear data retention policies
  - User control over cloud services

### 3. System Security
- [ ] **Code Signing**
  - Sign native libraries
  - Verify integrity of system hooks
  - Secure update mechanisms

## ✅ Acceptance Criteria
- [ ] Context menus appear reliably in major applications
- [ ] Text selection and replacement work accurately
- [ ] Performance meets sub-2-second response targets
- [ ] System integration is stable and doesn't crash applications
- [ ] Works across major Linux desktop environments
- [ ] Proper error handling and graceful fallbacks

## 📊 Estimated Effort
**Time**: 4-6 weeks  
**Complexity**: Very High  
**Priority**: Critical

## 🔗 Dependencies
- Completion of Phase 2 (Research & Planning)
- Completion of Phase 3 (AI Integration)
- Native development environment setup
- Test systems with different desktop environments

## ⚠️ Risk Factors
- **High Complexity**: System-level integration is inherently complex
- **Platform Fragmentation**: Many different Linux configurations to support
- **Security Restrictions**: Modern systems may restrict system hooks
- **Maintenance Burden**: System updates may break integration

**Comment by bekaIva** [comment]
## 🔧 Phase 4 Implementation Started

Successfully started Phase 4 - the most challenging part of our project: **system-wide context menu injection**.

### 📋 **Current Status**
- ✅ **Branch Created**: `phase-4-native-implementation`
- ✅ **Native Library Structure**: Complete C++ codebase with 7 core modules
- ✅ **Build System**: CMake configuration with all dependencies
- ✅ **FFI Interface**: Flutter bindings architecture ready
- 🔧 **Build Issues**: Identified and fixing specific compilation errors

### 🏗️ **Native Library Architecture**
Built comprehensive native library with:

#### **Core Modules:**
1. **`system_hooks.cpp`** - Main orchestration and FFI interface
2. **`text_selection_monitor.cpp`** - X11 primary selection monitoring via xclip
3. **`context_menu_injector.cpp`** - GTK context menu with global hotkey (Ctrl+Alt+T)
4. **`dbus_service.cpp`** - IPC communication with Flutter app
5. **`text_replacement.cpp`** - Advanced text replacement via clipboard + keyboard simulation
6. **`instant_translator.h`** - Complete FFI interface definition
7. **`main.cpp`** - Standalone test application

#### **Technical Implementation:**
- **Text Selection**: X11 primary selection monitoring using proven `xclip` approach from Phase 2
- **Context Menu**: GTK overlay menu system with mouse position detection
- **Hotkey System**: Global Ctrl+Alt+T hotkey monitoring via X11 events
- **Text Replacement**: Multi-method approach (clipboard + keyboard simulation)
- **IPC**: D-Bus service for Flutter communication
- **Threading**: Multi-threaded design with GTK main loop in separate thread

### 🐛 **Build Issues Identified**
Currently fixing compilation errors (typical for low-level system integration):

1. **D-Bus Headers**: Need `libdbus-glib-1-dev` instead of `libdbus-1-dev`
2. **X11 KeySyms**: Missing `#include <X11/keysym.h>` for key definitions
3. **Function Scope**: Need proper header includes for cross-module function calls
4. **GLib API**: Deprecated `g_thread_init` and incorrect `g_idle_add_full` usage

### 🎯 **Next Steps**
1. **Fix Build Issues**: Address compilation errors (in progress)
2. **Test Native Library**: Standalone testing with `instant_translator_test`
3. **Flutter Integration**: Complete FFI bindings and test end-to-end
4. **System Testing**: Verify context menu injection across applications

### 💡 **Why This Is The Most Challenging Phase**
Phase 4 requires:
- Low-level X11 programming for text selection and keyboard simulation
- GTK programming for context menu injection
- Multi-threaded design with proper synchronization
- D-Bus IPC programming for process communication
- FFI interface design for Flutter integration
- Cross-application compatibility testing

This is exactly the kind of system-level programming that makes instant translation challenging but powerful!

### 🔧 **Technical Approach Validation**
Our Phase 2 research is proving correct:
- ✅ **X11 + GTK + D-Bus** architecture works on Linux Mint 22.1/Cinnamon
- ✅ **xclip-based text selection** more reliable than direct X11 selection API
- ✅ **GTK overlay menus** better than LD_PRELOAD injection
- ✅ **Global hotkey fallback** provides universal access method

Currently debugging and will have working native library soon! 🚀
